//
//  Anchors+DSL_Tests.swift
//  TwentyLayout-iOS Tests
//
//  Created by Jérôme Alves on 13/01/2020.
//  Copyright © 2020 TwentyLayout. All rights reserved.
//

import XCTest
@testable import TwentyLayout

class Anchors_DSL_Tests: XCTestCase {

    let sut = UIView()

    func testAnchor1() {
        XCTAssertType(sut.anchors.top,                  SingleAnchor <UIView, Top>.self)
        XCTAssertType(sut.anchors.left,                 SingleAnchor <UIView, Left>.self)
        XCTAssertType(sut.anchors.right,                SingleAnchor <UIView, Right>.self)
        XCTAssertType(sut.anchors.bottom,               SingleAnchor <UIView, Bottom>.self)
        XCTAssertType(sut.anchors.leading,              SingleAnchor <UIView, Leading>.self)
        XCTAssertType(sut.anchors.trailing,             SingleAnchor <UIView, Trailing>.self)
        XCTAssertType(sut.anchors.topMargin,            SingleAnchor <UIView, TopMargin>.self)
        XCTAssertType(sut.anchors.leftMargin,           SingleAnchor <UIView, LeftMargin>.self)
        XCTAssertType(sut.anchors.rightMargin,          SingleAnchor <UIView, RightMargin>.self)
        XCTAssertType(sut.anchors.bottomMargin,         SingleAnchor <UIView, BottomMargin>.self)
        XCTAssertType(sut.anchors.leadingMargin,        SingleAnchor <UIView, LeadingMargin>.self)
        XCTAssertType(sut.anchors.trailingMargin,       SingleAnchor <UIView, TrailingMargin>.self)
        XCTAssertType(sut.anchors.centerX,              SingleAnchor <UIView, CenterX>.self)
        XCTAssertType(sut.anchors.centerY,              SingleAnchor <UIView, CenterY>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins, SingleAnchor <UIView, CenterXWithinMargins>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins, SingleAnchor <UIView, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.width,                SingleAnchor <UIView, Width>.self)
        XCTAssertType(sut.anchors.height,               SingleAnchor <UIView, Height>.self)
        XCTAssertType(sut.anchors.firstBaseline,        SingleAnchor <UIView, FirstBaseline>.self)
        XCTAssertType(sut.anchors.lastBaseline,         SingleAnchor <UIView, LastBaseline>.self)
    }

    func testAnchor2() {
        XCTAssertType(sut.anchors.top.top,                  SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.top.left,                 PointAnchor <UIView, Left, Top>.self)
        XCTAssertType(sut.anchors.top.right,                PointAnchor <UIView, Right, Top>.self)
        XCTAssertType(sut.anchors.top.bottom,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.top.leading,              PointAnchor <UIView, Leading, Top>.self)
        XCTAssertType(sut.anchors.top.trailing,             PointAnchor <UIView, Trailing, Top>.self)
        XCTAssertType(sut.anchors.top.topMargin,            SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.top.leftMargin,           PointAnchor <UIView, LeftMargin, Top>.self)
        XCTAssertType(sut.anchors.top.rightMargin,          PointAnchor <UIView, RightMargin, Top>.self)
        XCTAssertType(sut.anchors.top.bottomMargin,         SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.top.leadingMargin,        PointAnchor <UIView, LeadingMargin, Top>.self)
        XCTAssertType(sut.anchors.top.trailingMargin,       PointAnchor <UIView, TrailingMargin, Top>.self)
        XCTAssertType(sut.anchors.top.centerX,              PointAnchor <UIView, CenterX, Top>.self)
        XCTAssertType(sut.anchors.top.centerY,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.top.centerXWithinMargins, PointAnchor <UIView, CenterXWithinMargins, Top>.self)
        XCTAssertType(sut.anchors.top.centerYWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.top.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.top.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.top.firstBaseline,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.top.lastBaseline,         SetAnchor   <UIView>.self)

        XCTAssertType(sut.anchors.left.top,                  PointAnchor <UIView, Left, Top>.self)
        XCTAssertType(sut.anchors.left.left,                 SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.left.right,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.left.bottom,               PointAnchor <UIView, Left, Bottom>.self)
        XCTAssertType(sut.anchors.left.leading,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.left.trailing,             SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.left.topMargin,            PointAnchor <UIView, Left, TopMargin>.self)
        XCTAssertType(sut.anchors.left.leftMargin,           SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.left.rightMargin,          SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.left.bottomMargin,         PointAnchor <UIView, Left, BottomMargin>.self)
        XCTAssertType(sut.anchors.left.leadingMargin,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.left.trailingMargin,       SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.left.centerX,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.left.centerY,              PointAnchor <UIView, Left, CenterY>.self)
        XCTAssertType(sut.anchors.left.centerXWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.left.centerYWithinMargins, PointAnchor <UIView, Left, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.left.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.left.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.left.firstBaseline,        PointAnchor <UIView, Left, FirstBaseline>.self)
        XCTAssertType(sut.anchors.left.lastBaseline,         PointAnchor <UIView, Left, LastBaseline>.self)

        XCTAssertType(sut.anchors.right.top,                  PointAnchor <UIView, Right, Top>.self)
        XCTAssertType(sut.anchors.right.left,                 SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.right.right,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.right.bottom,               PointAnchor <UIView, Right, Bottom>.self)
        XCTAssertType(sut.anchors.right.leading,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.right.trailing,             SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.right.topMargin,            PointAnchor <UIView, Right, TopMargin>.self)
        XCTAssertType(sut.anchors.right.leftMargin,           SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.right.rightMargin,          SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.right.bottomMargin,         PointAnchor <UIView, Right, BottomMargin>.self)
        XCTAssertType(sut.anchors.right.leadingMargin,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.right.trailingMargin,       SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.right.centerX,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.right.centerY,              PointAnchor <UIView, Right, CenterY>.self)
        XCTAssertType(sut.anchors.right.centerXWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.right.centerYWithinMargins, PointAnchor <UIView, Right, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.right.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.right.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.right.firstBaseline,        PointAnchor <UIView, Right, FirstBaseline>.self)
        XCTAssertType(sut.anchors.right.lastBaseline,         PointAnchor <UIView, Right, LastBaseline>.self)

        XCTAssertType(sut.anchors.bottom.top,                  SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottom.left,                 PointAnchor <UIView, Left, Bottom>.self)
        XCTAssertType(sut.anchors.bottom.right,                PointAnchor <UIView, Right, Bottom>.self)
        XCTAssertType(sut.anchors.bottom.bottom,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottom.leading,              PointAnchor <UIView, Leading, Bottom>.self)
        XCTAssertType(sut.anchors.bottom.trailing,             PointAnchor <UIView, Trailing, Bottom>.self)
        XCTAssertType(sut.anchors.bottom.topMargin,            SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottom.leftMargin,           PointAnchor <UIView, LeftMargin, Bottom>.self)
        XCTAssertType(sut.anchors.bottom.rightMargin,          PointAnchor <UIView, RightMargin, Bottom>.self)
        XCTAssertType(sut.anchors.bottom.bottomMargin,         SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottom.leadingMargin,        PointAnchor <UIView, LeadingMargin, Bottom>.self)
        XCTAssertType(sut.anchors.bottom.trailingMargin,       PointAnchor <UIView, TrailingMargin, Bottom>.self)
        XCTAssertType(sut.anchors.bottom.centerX,              PointAnchor <UIView, CenterX, Bottom>.self)
        XCTAssertType(sut.anchors.bottom.centerY,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottom.centerXWithinMargins, PointAnchor <UIView, CenterXWithinMargins, Bottom>.self)
        XCTAssertType(sut.anchors.bottom.centerYWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottom.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottom.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottom.firstBaseline,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottom.lastBaseline,         SetAnchor   <UIView>.self)

        XCTAssertType(sut.anchors.leading.top,                  PointAnchor <UIView, Leading, Top>.self)
        XCTAssertType(sut.anchors.leading.left,                 SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leading.right,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leading.bottom,               PointAnchor <UIView, Leading, Bottom>.self)
        XCTAssertType(sut.anchors.leading.leading,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leading.trailing,             SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leading.topMargin,            PointAnchor <UIView, Leading, TopMargin>.self)
        XCTAssertType(sut.anchors.leading.leftMargin,           SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leading.rightMargin,          SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leading.bottomMargin,         PointAnchor <UIView, Leading, BottomMargin>.self)
        XCTAssertType(sut.anchors.leading.leadingMargin,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leading.trailingMargin,       SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leading.centerX,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leading.centerY,              PointAnchor <UIView, Leading, CenterY>.self)
        XCTAssertType(sut.anchors.leading.centerXWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leading.centerYWithinMargins, PointAnchor <UIView, Leading, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.leading.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leading.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leading.firstBaseline,        PointAnchor <UIView, Leading, FirstBaseline>.self)
        XCTAssertType(sut.anchors.leading.lastBaseline,         PointAnchor <UIView, Leading, LastBaseline>.self)

        XCTAssertType(sut.anchors.trailing.top,                  PointAnchor <UIView, Trailing, Top>.self)
        XCTAssertType(sut.anchors.trailing.left,                 SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailing.right,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailing.bottom,               PointAnchor <UIView, Trailing, Bottom>.self)
        XCTAssertType(sut.anchors.trailing.leading,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailing.trailing,             SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailing.topMargin,            PointAnchor <UIView, Trailing, TopMargin>.self)
        XCTAssertType(sut.anchors.trailing.leftMargin,           SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailing.rightMargin,          SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailing.bottomMargin,         PointAnchor <UIView, Trailing, BottomMargin>.self)
        XCTAssertType(sut.anchors.trailing.leadingMargin,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailing.trailingMargin,       SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailing.centerX,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailing.centerY,              PointAnchor <UIView, Trailing, CenterY>.self)
        XCTAssertType(sut.anchors.trailing.centerXWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailing.centerYWithinMargins, PointAnchor <UIView, Trailing, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.trailing.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailing.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailing.firstBaseline,        PointAnchor <UIView, Trailing, FirstBaseline>.self)
        XCTAssertType(sut.anchors.trailing.lastBaseline,         PointAnchor <UIView, Trailing, LastBaseline>.self)

        XCTAssertType(sut.anchors.topMargin.top,                  SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.topMargin.left,                 PointAnchor <UIView, Left, TopMargin>.self)
        XCTAssertType(sut.anchors.topMargin.right,                PointAnchor <UIView, Right, TopMargin>.self)
        XCTAssertType(sut.anchors.topMargin.bottom,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.topMargin.leading,              PointAnchor <UIView, Leading, TopMargin>.self)
        XCTAssertType(sut.anchors.topMargin.trailing,             PointAnchor <UIView, Trailing, TopMargin>.self)
        XCTAssertType(sut.anchors.topMargin.topMargin,            SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.topMargin.leftMargin,           PointAnchor <UIView, LeftMargin, TopMargin>.self)
        XCTAssertType(sut.anchors.topMargin.rightMargin,          PointAnchor <UIView, RightMargin, TopMargin>.self)
        XCTAssertType(sut.anchors.topMargin.bottomMargin,         SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.topMargin.leadingMargin,        PointAnchor <UIView, LeadingMargin, TopMargin>.self)
        XCTAssertType(sut.anchors.topMargin.trailingMargin,       PointAnchor <UIView, TrailingMargin, TopMargin>.self)
        XCTAssertType(sut.anchors.topMargin.centerX,              PointAnchor <UIView, CenterX, TopMargin>.self)
        XCTAssertType(sut.anchors.topMargin.centerY,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.topMargin.centerXWithinMargins, PointAnchor <UIView, CenterXWithinMargins, TopMargin>.self)
        XCTAssertType(sut.anchors.topMargin.centerYWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.topMargin.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.topMargin.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.topMargin.firstBaseline,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.topMargin.lastBaseline,         SetAnchor   <UIView>.self)

        XCTAssertType(sut.anchors.leftMargin.top,                  PointAnchor <UIView, LeftMargin, Top>.self)
        XCTAssertType(sut.anchors.leftMargin.left,                 SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leftMargin.right,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leftMargin.bottom,               PointAnchor <UIView, LeftMargin, Bottom>.self)
        XCTAssertType(sut.anchors.leftMargin.leading,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leftMargin.trailing,             SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leftMargin.topMargin,            PointAnchor <UIView, LeftMargin, TopMargin>.self)
        XCTAssertType(sut.anchors.leftMargin.leftMargin,           SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leftMargin.rightMargin,          SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leftMargin.bottomMargin,         PointAnchor <UIView, LeftMargin, BottomMargin>.self)
        XCTAssertType(sut.anchors.leftMargin.leadingMargin,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leftMargin.trailingMargin,       SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leftMargin.centerX,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leftMargin.centerY,              PointAnchor <UIView, LeftMargin, CenterY>.self)
        XCTAssertType(sut.anchors.leftMargin.centerXWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leftMargin.centerYWithinMargins, PointAnchor <UIView, LeftMargin, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.leftMargin.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leftMargin.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leftMargin.firstBaseline,        PointAnchor <UIView, LeftMargin, FirstBaseline>.self)
        XCTAssertType(sut.anchors.leftMargin.lastBaseline,         PointAnchor <UIView, LeftMargin, LastBaseline>.self)

        XCTAssertType(sut.anchors.rightMargin.top,                  PointAnchor <UIView, RightMargin, Top>.self)
        XCTAssertType(sut.anchors.rightMargin.left,                 SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.rightMargin.right,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.rightMargin.bottom,               PointAnchor <UIView, RightMargin, Bottom>.self)
        XCTAssertType(sut.anchors.rightMargin.leading,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.rightMargin.trailing,             SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.rightMargin.topMargin,            PointAnchor <UIView, RightMargin, TopMargin>.self)
        XCTAssertType(sut.anchors.rightMargin.leftMargin,           SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.rightMargin.rightMargin,          SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.rightMargin.bottomMargin,         PointAnchor <UIView, RightMargin, BottomMargin>.self)
        XCTAssertType(sut.anchors.rightMargin.leadingMargin,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.rightMargin.trailingMargin,       SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.rightMargin.centerX,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.rightMargin.centerY,              PointAnchor <UIView, RightMargin, CenterY>.self)
        XCTAssertType(sut.anchors.rightMargin.centerXWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.rightMargin.centerYWithinMargins, PointAnchor <UIView, RightMargin, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.rightMargin.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.rightMargin.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.rightMargin.firstBaseline,        PointAnchor <UIView, RightMargin, FirstBaseline>.self)
        XCTAssertType(sut.anchors.rightMargin.lastBaseline,         PointAnchor <UIView, RightMargin, LastBaseline>.self)

        XCTAssertType(sut.anchors.bottomMargin.top,                  SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottomMargin.left,                 PointAnchor <UIView, Left, BottomMargin>.self)
        XCTAssertType(sut.anchors.bottomMargin.right,                PointAnchor <UIView, Right, BottomMargin>.self)
        XCTAssertType(sut.anchors.bottomMargin.bottom,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottomMargin.leading,              PointAnchor <UIView, Leading, BottomMargin>.self)
        XCTAssertType(sut.anchors.bottomMargin.trailing,             PointAnchor <UIView, Trailing, BottomMargin>.self)
        XCTAssertType(sut.anchors.bottomMargin.topMargin,            SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottomMargin.leftMargin,           PointAnchor <UIView, LeftMargin, BottomMargin>.self)
        XCTAssertType(sut.anchors.bottomMargin.rightMargin,          PointAnchor <UIView, RightMargin, BottomMargin>.self)
        XCTAssertType(sut.anchors.bottomMargin.bottomMargin,         SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottomMargin.leadingMargin,        PointAnchor <UIView, LeadingMargin, BottomMargin>.self)
        XCTAssertType(sut.anchors.bottomMargin.trailingMargin,       PointAnchor <UIView, TrailingMargin, BottomMargin>.self)
        XCTAssertType(sut.anchors.bottomMargin.centerX,              PointAnchor <UIView, CenterX, BottomMargin>.self)
        XCTAssertType(sut.anchors.bottomMargin.centerY,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottomMargin.centerXWithinMargins, PointAnchor <UIView, CenterXWithinMargins, BottomMargin>.self)
        XCTAssertType(sut.anchors.bottomMargin.centerYWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottomMargin.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottomMargin.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottomMargin.firstBaseline,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.bottomMargin.lastBaseline,         SetAnchor   <UIView>.self)

        XCTAssertType(sut.anchors.leadingMargin.top,                  PointAnchor <UIView, LeadingMargin, Top>.self)
        XCTAssertType(sut.anchors.leadingMargin.left,                 SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leadingMargin.right,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leadingMargin.bottom,               PointAnchor <UIView, LeadingMargin, Bottom>.self)
        XCTAssertType(sut.anchors.leadingMargin.leading,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leadingMargin.trailing,             SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leadingMargin.topMargin,            PointAnchor <UIView, LeadingMargin, TopMargin>.self)
        XCTAssertType(sut.anchors.leadingMargin.leftMargin,           SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leadingMargin.rightMargin,          SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leadingMargin.bottomMargin,         PointAnchor <UIView, LeadingMargin, BottomMargin>.self)
        XCTAssertType(sut.anchors.leadingMargin.leadingMargin,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leadingMargin.trailingMargin,       SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leadingMargin.centerX,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leadingMargin.centerY,              PointAnchor <UIView, LeadingMargin, CenterY>.self)
        XCTAssertType(sut.anchors.leadingMargin.centerXWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leadingMargin.centerYWithinMargins, PointAnchor <UIView, LeadingMargin, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.leadingMargin.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leadingMargin.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.leadingMargin.firstBaseline,        PointAnchor <UIView, LeadingMargin, FirstBaseline>.self)
        XCTAssertType(sut.anchors.leadingMargin.lastBaseline,         PointAnchor <UIView, LeadingMargin, LastBaseline>.self)

        XCTAssertType(sut.anchors.trailingMargin.top,                  PointAnchor <UIView, TrailingMargin, Top>.self)
        XCTAssertType(sut.anchors.trailingMargin.left,                 SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailingMargin.right,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailingMargin.bottom,               PointAnchor <UIView, TrailingMargin, Bottom>.self)
        XCTAssertType(sut.anchors.trailingMargin.leading,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailingMargin.trailing,             SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailingMargin.topMargin,            PointAnchor <UIView, TrailingMargin, TopMargin>.self)
        XCTAssertType(sut.anchors.trailingMargin.leftMargin,           SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailingMargin.rightMargin,          SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailingMargin.bottomMargin,         PointAnchor <UIView, TrailingMargin, BottomMargin>.self)
        XCTAssertType(sut.anchors.trailingMargin.leadingMargin,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailingMargin.trailingMargin,       SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailingMargin.centerX,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailingMargin.centerY,              PointAnchor <UIView, TrailingMargin, CenterY>.self)
        XCTAssertType(sut.anchors.trailingMargin.centerXWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailingMargin.centerYWithinMargins, PointAnchor <UIView, TrailingMargin, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.trailingMargin.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailingMargin.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.trailingMargin.firstBaseline,        PointAnchor <UIView, TrailingMargin, FirstBaseline>.self)
        XCTAssertType(sut.anchors.trailingMargin.lastBaseline,         PointAnchor <UIView, TrailingMargin, LastBaseline>.self)

        XCTAssertType(sut.anchors.centerX.top,                  PointAnchor <UIView, CenterX, Top>.self)
        XCTAssertType(sut.anchors.centerX.left,                 SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerX.right,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerX.bottom,               PointAnchor <UIView, CenterX, Bottom>.self)
        XCTAssertType(sut.anchors.centerX.leading,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerX.trailing,             SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerX.topMargin,            PointAnchor <UIView, CenterX, TopMargin>.self)
        XCTAssertType(sut.anchors.centerX.leftMargin,           SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerX.rightMargin,          SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerX.bottomMargin,         PointAnchor <UIView, CenterX, BottomMargin>.self)
        XCTAssertType(sut.anchors.centerX.leadingMargin,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerX.trailingMargin,       SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerX.centerX,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerX.centerY,              PointAnchor <UIView, CenterX, CenterY>.self)
        XCTAssertType(sut.anchors.centerX.centerXWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerX.centerYWithinMargins, PointAnchor <UIView, CenterX, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.centerX.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerX.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerX.firstBaseline,        PointAnchor <UIView, CenterX, FirstBaseline>.self)
        XCTAssertType(sut.anchors.centerX.lastBaseline,         PointAnchor <UIView, CenterX, LastBaseline>.self)

        XCTAssertType(sut.anchors.centerY.top,                  SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerY.left,                 PointAnchor <UIView, Left, CenterY>.self)
        XCTAssertType(sut.anchors.centerY.right,                PointAnchor <UIView, Right, CenterY>.self)
        XCTAssertType(sut.anchors.centerY.bottom,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerY.leading,              PointAnchor <UIView, Leading, CenterY>.self)
        XCTAssertType(sut.anchors.centerY.trailing,             PointAnchor <UIView, Trailing, CenterY>.self)
        XCTAssertType(sut.anchors.centerY.topMargin,            SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerY.leftMargin,           PointAnchor <UIView, LeftMargin, CenterY>.self)
        XCTAssertType(sut.anchors.centerY.rightMargin,          PointAnchor <UIView, RightMargin, CenterY>.self)
        XCTAssertType(sut.anchors.centerY.bottomMargin,         SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerY.leadingMargin,        PointAnchor <UIView, LeadingMargin, CenterY>.self)
        XCTAssertType(sut.anchors.centerY.trailingMargin,       PointAnchor <UIView, TrailingMargin, CenterY>.self)
        XCTAssertType(sut.anchors.centerY.centerX,              PointAnchor <UIView, CenterX, CenterY>.self)
        XCTAssertType(sut.anchors.centerY.centerY,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerY.centerXWithinMargins, PointAnchor <UIView, CenterXWithinMargins, CenterY>.self)
        XCTAssertType(sut.anchors.centerY.centerYWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerY.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerY.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerY.firstBaseline,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerY.lastBaseline,         SetAnchor   <UIView>.self)

        XCTAssertType(sut.anchors.centerXWithinMargins.top,                  PointAnchor <UIView, CenterXWithinMargins, Top>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.left,                 SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.right,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.bottom,               PointAnchor <UIView, CenterXWithinMargins, Bottom>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.leading,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.trailing,             SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.topMargin,            PointAnchor <UIView, CenterXWithinMargins, TopMargin>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.leftMargin,           SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.rightMargin,          SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.bottomMargin,         PointAnchor <UIView, CenterXWithinMargins, BottomMargin>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.leadingMargin,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.trailingMargin,       SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.centerX,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.centerY,              PointAnchor <UIView, CenterXWithinMargins, CenterY>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.centerXWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.centerYWithinMargins, PointAnchor <UIView, CenterXWithinMargins, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.firstBaseline,        PointAnchor <UIView, CenterXWithinMargins, FirstBaseline>.self)
        XCTAssertType(sut.anchors.centerXWithinMargins.lastBaseline,         PointAnchor <UIView, CenterXWithinMargins, LastBaseline>.self)

        XCTAssertType(sut.anchors.centerYWithinMargins.top,                  SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.left,                 PointAnchor <UIView, Left, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.right,                PointAnchor <UIView, Right, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.bottom,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.leading,              PointAnchor <UIView, Leading, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.trailing,             PointAnchor <UIView, Trailing, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.topMargin,            SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.leftMargin,           PointAnchor <UIView, LeftMargin, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.rightMargin,          PointAnchor <UIView, RightMargin, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.bottomMargin,         SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.leadingMargin,        PointAnchor <UIView, LeadingMargin, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.trailingMargin,       PointAnchor <UIView, TrailingMargin, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.centerX,              PointAnchor <UIView, CenterX, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.centerY,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.centerXWithinMargins, PointAnchor <UIView, CenterXWithinMargins, CenterYWithinMargins>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.centerYWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.firstBaseline,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.centerYWithinMargins.lastBaseline,         SetAnchor   <UIView>.self)
 
        XCTAssertType(sut.anchors.width.top,                  SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.left,                 SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.right,                SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.bottom,               SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.leading,              SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.trailing,             SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.topMargin,            SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.leftMargin,           SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.rightMargin,          SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.bottomMargin,         SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.leadingMargin,        SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.trailingMargin,       SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.centerX,              SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.centerY,              SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.centerXWithinMargins, SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.centerYWithinMargins, SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.width,                SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.height,               SizeAnchor <UIView>.self)
        XCTAssertType(sut.anchors.width.firstBaseline,        SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.width.lastBaseline,         SetAnchor  <UIView>.self)

        XCTAssertType(sut.anchors.height.top,                  SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.left,                 SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.right,                SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.bottom,               SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.leading,              SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.trailing,             SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.topMargin,            SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.leftMargin,           SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.rightMargin,          SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.bottomMargin,         SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.leadingMargin,        SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.trailingMargin,       SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.centerX,              SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.centerY,              SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.centerXWithinMargins, SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.centerYWithinMargins, SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.width,                SizeAnchor <UIView>.self)
        XCTAssertType(sut.anchors.height.height,               SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.firstBaseline,        SetAnchor  <UIView>.self)
        XCTAssertType(sut.anchors.height.lastBaseline,         SetAnchor  <UIView>.self)

        XCTAssertType(sut.anchors.firstBaseline.top,                  SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.firstBaseline.left,                 PointAnchor <UIView, Left, FirstBaseline>.self)
        XCTAssertType(sut.anchors.firstBaseline.right,                PointAnchor <UIView, Right, FirstBaseline>.self)
        XCTAssertType(sut.anchors.firstBaseline.bottom,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.firstBaseline.leading,              PointAnchor <UIView, Leading, FirstBaseline>.self)
        XCTAssertType(sut.anchors.firstBaseline.trailing,             PointAnchor <UIView, Trailing, FirstBaseline>.self)
        XCTAssertType(sut.anchors.firstBaseline.topMargin,            SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.firstBaseline.leftMargin,           PointAnchor <UIView, LeftMargin, FirstBaseline>.self)
        XCTAssertType(sut.anchors.firstBaseline.rightMargin,          PointAnchor <UIView, RightMargin, FirstBaseline>.self)
        XCTAssertType(sut.anchors.firstBaseline.bottomMargin,         SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.firstBaseline.leadingMargin,        PointAnchor <UIView, LeadingMargin, FirstBaseline>.self)
        XCTAssertType(sut.anchors.firstBaseline.trailingMargin,       PointAnchor <UIView, TrailingMargin, FirstBaseline>.self)
        XCTAssertType(sut.anchors.firstBaseline.centerX,              PointAnchor <UIView, CenterX, FirstBaseline>.self)
        XCTAssertType(sut.anchors.firstBaseline.centerY,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.firstBaseline.centerXWithinMargins, PointAnchor <UIView, CenterXWithinMargins, FirstBaseline>.self)
        XCTAssertType(sut.anchors.firstBaseline.centerYWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.firstBaseline.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.firstBaseline.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.firstBaseline.firstBaseline,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.firstBaseline.lastBaseline,         SetAnchor   <UIView>.self)

        XCTAssertType(sut.anchors.lastBaseline.top,                  SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.lastBaseline.left,                 PointAnchor <UIView, Left, LastBaseline>.self)
        XCTAssertType(sut.anchors.lastBaseline.right,                PointAnchor <UIView, Right, LastBaseline>.self)
        XCTAssertType(sut.anchors.lastBaseline.bottom,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.lastBaseline.leading,              PointAnchor <UIView, Leading, LastBaseline>.self)
        XCTAssertType(sut.anchors.lastBaseline.trailing,             PointAnchor <UIView, Trailing, LastBaseline>.self)
        XCTAssertType(sut.anchors.lastBaseline.topMargin,            SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.lastBaseline.leftMargin,           PointAnchor <UIView, LeftMargin, LastBaseline>.self)
        XCTAssertType(sut.anchors.lastBaseline.rightMargin,          PointAnchor <UIView, RightMargin, LastBaseline>.self)
        XCTAssertType(sut.anchors.lastBaseline.bottomMargin,         SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.lastBaseline.leadingMargin,        PointAnchor <UIView, LeadingMargin, LastBaseline>.self)
        XCTAssertType(sut.anchors.lastBaseline.trailingMargin,       PointAnchor <UIView, TrailingMargin, LastBaseline>.self)
        XCTAssertType(sut.anchors.lastBaseline.centerX,              PointAnchor <UIView, CenterX, LastBaseline>.self)
        XCTAssertType(sut.anchors.lastBaseline.centerY,              SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.lastBaseline.centerXWithinMargins, PointAnchor <UIView, CenterXWithinMargins, LastBaseline>.self)
        XCTAssertType(sut.anchors.lastBaseline.centerYWithinMargins, SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.lastBaseline.width,                SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.lastBaseline.height,               SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.lastBaseline.firstBaseline,        SetAnchor   <UIView>.self)
        XCTAssertType(sut.anchors.lastBaseline.lastBaseline,         SetAnchor   <UIView>.self)
    
        XCTAssertType(sut.anchors.size, SizeAnchor <UIView>.self)
        XCTAssertType(sut.anchors.center, PointAnchor <UIView, CenterX, CenterY>.self)
        XCTAssertType(sut.anchors.centerWithinMargins, PointAnchor <UIView, CenterXWithinMargins, CenterYWithinMargins>.self)
    }

    func testAnchor4() {
        XCTAssertType(sut.anchors.edges,   EdgesAnchor <UIView, Top, Bottom, Left, Right>.self)
        XCTAssertType(sut.anchors.margins, EdgesAnchor <UIView, TopMargin, BottomMargin, LeftMargin, RightMargin>.self)
        XCTAssertType(sut.anchors.directionalEdges,   EdgesAnchor <UIView, Top, Bottom, Leading, Trailing>.self)
        XCTAssertType(sut.anchors.directionalMargins, EdgesAnchor <UIView, TopMargin, BottomMargin, LeadingMargin, TrailingMargin>.self)
    }
}
